name: Frontend CI/CD

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/movie-frontend:latest ./frontend

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/movie-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy frontend to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/movie-frontend:latest

            docker rm -f movie-frontend || true

            docker run -d \
              --name movie-frontend \
              -p 80:80 \
              ${{ secrets.DOCKERHUB_USERNAME }}/movie-frontend:latest
