name: Frontend CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - "scripts/**"
      - ".github/workflows/frontend.yml"

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push frontend
        run: bash scripts/build-and-push.sh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE: movie-frontend
          CONTEXT: ./frontend

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy frontend to EC2
        run: bash scripts/deploy.sh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE: movie-frontend
          CONTAINER: movie-frontend
          PORT: 80
          EXTRA_DOCKER_ARGS: ""
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
